---
version: "2.0"

services:
  peppermintpostgres:
    image: postgres:15-alpine
    env:
      - POSTGRES_DB=peppermint
      - POSTGRES_USER=peppermint
      - POSTGRES_PASSWORD=1234
    expose:
      - port: 5432
        as: 5432
        to:
          - service: peppermint

  peppermint:
    image: pepperlabs/peppermint:latest
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 5003
        as: 5003
        to:
          - global: true
    env:
      - DB_USERNAME=peppermint
      - DB_PASSWORD=1234
      - DB_HOST=peppermintpostgres
      - SECRET=peppermint4life
    depends_on:
      - peppermintpostgres

profiles:
  compute:
    peppermint:
      resources:
        cpu:
          units: 2
        memory:
          size: 1gb
        storage:
          - size: 20Gi
    peppermintpostgres:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 10Gi

  placement:
    dcloud:
      pricing:
        peppermint:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
        peppermintpostgres:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 50000

deployment:
  peppermint:
    dcloud:
      profile: peppermint
      count: 1
  peppermintpostgres:
    dcloud:
      profile: peppermintpostgres
      count: 1
