---

- name: Required applications
  ansible.builtin.apt:
    name: "{{ applications_to_install }}"
    state: present

- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
